### ISSUE TITLE
xenstore_common.c: write_to_xenstore() fd_pre and fd_aft

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#18] opened 2017-01-24 03:35 UTC
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- xenstore_common.c: write_to_xenstore() fd_pre and fd_aft looks like an
  attempt to deal with race conditions in the daemon:
  - multiple threads working simultaneously
  - no concurrency controls to ensure atomic use of xenstore writes
  - this can be solved either by
    - undoing all the threading or
    - by adding a new communication thread that all the other threads use
      to talk with xenstore or
    - adding pthread_cond_*() functions to ensure the xenstore interface
      is used by only one tool at a time or
    - set up the xenstore interface so it's ready to be used by the other
      threads before they start (see pthread_once), and then re-design all
      uses of xenstore to use only atomic operations.

Thanks

**Comment by UVP-Tools** [comment] 2017-02-24 09:30
Hi, Setharnold
Thank you.

xs_write is a thread-safe interface, so there is no need to add concurrency control before calling it. The log recording the handle value is to check whether the failure of write is caused by the handle change. We will close this issue.

**Closed as completed** 2017-03-09 00:18 UTC
